FROM ubuntu
MAINTAINER cliffrowley@gmail.com

USER root

RUN DEBIAN_FRONTEND=noninteractive \
  apt-get -y update && \
  apt-get install -q -y --no-install-recommends \
  ca-certificates build-essential git

ENV MVDSV_DIR=/usr/local/src/mvdsv

RUN git clone https://github.com/deurk/mvdsv $MVDSV_DIR

WORKDIR $MVDSV_DIR/build/make

RUN ./configure Linux && make
